AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  RDSUserName:
    Type: String
    Default: None
  RDSPassword:
    Type: String
    Default: None
    NoEcho: true
  RDSDBName:
    Type: String
    Default: None
  RDSHost:
    Type: String
    Default: None
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: graphql.handler
      Runtime: nodejs12.x
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
      Environment:
        Variables:
          PGUSER: !Ref RDSUserName
          PGHOST: !Ref RDSHost
          PGPASSWORD: !Ref RDSPassword
          PGDATABASE: !Ref RDSDBName
          PGPORT: 5432
